### ISSUE TITLE
NoClassDefFoundError: StackNavigationFactoryKt

### ISSUE THREAD

**Issue by sdzshn3** [arkivanov/Decompose#406] opened 2023-06-08 09:53 UTC
Hi Guys, I have a multiplatform application which has web, android and desktop.

To build JVM application for different OS (Windows, macOS, Linux), I'm using [Hydraulic Conveyor](https://conveyor.hydraulic.dev/)

When i'm trying to run the desktop application in windows using the command `conveyor run`, I'm getting an error as  
![Screenshot 2023-06-08 151913](https://github.com/arkivanov/Decompose/assets/36739949/e3630cf9-8898-403b-a3a5-eb9c8d9649ea)

The same happens when I run the task "runDistributable" also

I'm using these versions of Decompose 
```
api("com.arkivanov.decompose:decompose:1.0.0-alpha-05")
implementation("com.arkivanov.decompose:extensions-compose-jetbrains:1.0.0-compose-experimental")
```
at MainContent.kt:25, I have this
`val navigation = remember { StackNavigation<Screen>() }`

**Comment by arkivanov** [comment] 2023-06-08 10:05
I'm not familiar Hydraulic Conveyor, but this looks like Decompose is not included in the build (or in the class path, etc.).

**Comment by sdzshn3** [comment] 2023-06-08 10:10
@arkivanov I just tried to run "runDistributable" it is also giving the same error. However, application runs fine if I try to open the application using the play shortcut in Main.kt file.

There are no red squiggly lines in code

**Comment by arkivanov** [comment] 2023-06-08 10:29
A reproducer would help, it would be good if you could provide one? Without it it's pretty difficult.

**Comment by arkivanov** [comment] 2023-06-13 19:50
Closing this for now. Feel free to reopen if the issue is still there.

**Closed as not planned by arkivanov** 2023-06-13 19:50 UTC
Labels: question
