### ISSUE TITLE
Cannot access class 'androidx.compose.*'. Check your module classpath for missing or conflicting dependencies

### ISSUE THREAD

**Issue by ayitinya** [arkivanov/Decompose#568] opened 2023-12-09 12:32 UTC
decomposeVersion: = 3.0.0-alpha01
kotlin = "1.9.20"
jetbrains-compose = "1.5.10"

*repoduction*
Include the two dependencies for version 3.0.0-alpha01 in a fresh compose multiplatform project created with the [multiplatform wizard](https://kmp.jetbrains.com/)

[link to reproduction on gh](https://github.com/ayitinya/decompose-3.0.0-alpha01-error-reproduction.git)

*IDEs*
AS Iguana 2023.2.1 canary 17
Idea ultimate 2023.3

`Cannot access class 'androidx.compose.*'. Check your module classpath for missing or conflicting dependencies` shows up whenever you try to use a composable 

![image](https://github.com/arkivanov/Decompose/assets/78674026/d476611b-0faa-4924-a3df-a5ef43ebd2c9)

**Comment by arkivanov** [comment] 2023-12-09 12:54
This looks like a bug in Compose ore KMP. If you update Compose to `1.6.0-alpha01` then it works.

**Comment by ayitinya** [comment] 2023-12-09 13:01
> This looks like a bug in Compose ore KMP. If you update Compose to `1.6.0-alpha01` then it works.

can confirm, works in 1.6.0-alpha01

**Comment by arkivanov** [comment] 2023-12-09 13:05
Thanks! I asked about this issue in Kotlinlang Slack, I will update here.

**Comment by arkivanov** [comment] 2023-12-09 13:28
It looks like this issue: https://youtrack.jetbrains.com/issue/KT-62398.

Closing this issue as it's unrelated to Decompose.

**Closed as not planned by arkivanov** 2023-12-09 13:28 UTC

**Comment by DjuroRad** [comment] 2024-01-08 10:37
I can confirm that this worked for me also. Had a similar issue where IDE would consider a bunch of stuff an error
