### ISSUE TITLE
LazyColumn doesn't want to recompose on add item if using Children with stackAnimation()

### ISSUE THREAD

**Issue by denchic45** [arkivanov/Decompose#348] opened 2023-03-27 18:51 UTC
The video shows that when I switch to another screen and then return, the LazyColumn starts to behave incorrectly, it does not update the list of elements when a new element is added, unless the window is resized or switched to another screen again.

This happens if you use Children together with stackAnimation, without animation everything always works correctly when returning to the first screen

Videos:
- https://drive.google.com/file/d/1wl6wUnNQlamqHlLomWzHVWv9Lk3wB777/view?usp=sharing
- https://drive.google.com/file/d/1oA2U0gwota6YC59zn8zNQWW3ewgbSUGS/view?usp=sharing

Project:
https://github.com/denchic45/decompose-child-lazycolumn-bug

**Comment by arkivanov** [comment] 2023-03-27 19:04
Thanks for raising! This is likely for the same reason as #330 and #326. This might be already fixed in JB Compose `v1.3.1`. Otherwise, this will be fixed in the next release of Decompose. Current implementation depends on `movableContentOf`, turned out it has some bugs.

**Comment by arkivanov** [comment] 2023-03-27 20:56
I have just checked the reproducer project, it's indeed a duplicate of #326. The issue was fixed in JB Compose `v1.3.1`.

**Closed as not planned by arkivanov** 2023-03-27 20:56 UTC
Labels: bug, duplicate
