### ISSUE TITLE
Add ModalBottomSheet with Child Overlay example

### ISSUE THREAD

**Issue by AJIEKCX** [arkivanov/Decompose#261] opened 2022-11-15 06:21 UTC
Hello, it would be great to add an example how to work with ModalBottomSheet in Compose UI with Child Overlay and also make a convenient Composable function like a Children but for ModalBottomSheet. I've implemented this one and it's work, but may be it's not perfect solution:

```kotlin
@Composable
fun <C : Any, T : Any> ModalBottomSheetOverlay(
    childOverlay: ChildOverlay<C, T>,
    onDismiss: () -> Unit,
    sheetContent: @Composable (child: Child.Created<C, T>?) -> Unit,
    modifier: Modifier = Modifier,
    skipHalfExpanded: Boolean = false,
    sheetShape: Shape = MaterialTheme.shapes.large,
    sheetElevation: Dp = ModalBottomSheetDefaults.Elevation,
    sheetBackgroundColor: Color = MaterialTheme.colors.surface,
    sheetContentColor: Color = contentColorFor(sheetBackgroundColor),
    scrimColor: Color = ModalBottomSheetDefaults.scrimColor,
    content: @Composable () -> Unit
) {
    val overlay = childOverlay.overlay
    val bottomSheetState = rememberModalBottomSheetState(
        initialValue = ModalBottomSheetValue.Hidden,
        skipHalfExpanded = skipHalfExpanded,
        confirmStateChange = { value ->
            if (value == ModalBottomSheetValue.Hidden) {
                onDismiss()
                return@rememberModalBottomSheetState false
            }
            true
        }
    )
    var lastOverlay by remember { mutableStateOf(overlay) }

    SideEffect {
        if (overlay != null) {
            lastOverlay = overlay
        }
    }

    LaunchedEffect(overlay) {
        if (overlay != null) {
            bottomSheetState.show()
        } else {
            bottomSheetState.hide()
            lastOverlay = null
        }
    }

    ModalBottomSheetLayout(
        sheetContent = {
            sheetContent.invoke(overlay ?: lastOverlay)
        },
        sheetState = bottomSheetState,
        modifier = modifier,
        sheetShape = sheetShape,
        sheetElevation = sheetElevation,
        sheetBackgroundColor = sheetBackgroundColor,
        sheetContentColor = sheetContentColor,
        scrimColor = scrimColor,
        content = content
    )
}
```

**Comment by arkivanov** [comment] 2022-11-15 19:37
Hello and thanks for raising! There are many different APIs in Jetpack Compose, it's pretty difficult to cover everything in samples and keep the samples simple and readable. The same is applicable for adding public APIs for Jetpack Compose. For now I'm not convinced, as I'm trying hard to keep the library as simple as possible.

Meantime, here is what I came up with, feel free to use it!

**The API**

```kotlin
private val emptyContent: @Composable ColumnScope.() -> Unit = { Spacer(Modifier.height(1.dp)) }

@ExperimentalMaterialApi
class OverlayModalBottomSheetState(
    val sheetContent: State<@Composable ColumnScope.() -> Unit>,
    val sheetState: ModalBottomSheetState,
)

@OptIn(ExperimentalMaterialApi::class)
@Composable
fun <C : Any, T : Any> rememberOverlayModalBottomSheetState(
    overlay: Value<ChildOverlay<C, T>>,
    onDismiss: () -> Unit,
    sheetContent: @Composable (child: Child.Created<C, T>) -> Unit,
): OverlayModalBottomSheetState {
    val overlayState by overlay.subscribeAsState()
    val child: Child.Created<C, T>? = overlayState.overlay

    val sheetState =
        rememberModalBottomSheetState(
            initialValue = ModalBottomSheetValue.Hidden,
            confirmStateChange = { state ->
                if (state == ModalBottomSheetValue.Hidden) {
                    onDismiss()
                }
                true
            }
        )

    val childContent = remember { mutableStateOf(emptyContent) }

    LaunchedEffect(child == null) {
        if (child == null) {
            sheetState.hide()
            childContent.value = emptyContent
        } else {
            sheetState.show()
        }
    }

    DisposableEffect(child) {
        if (child != null) {
            childContent.value = { sheetContent(child) }
        }
        onDispose {}
    }

    return remember { OverlayModalBottomSheetState(sheetContent = childContent, sheetState = sheetState) }
}
```

**Usage**

```kotlin
val sheetState =
    rememberOverlayModalBottomSheetState(
        overlay = component.bottomSheet,
        onDismiss = component::dismissBottomSheet,
    ) {
        when (val child = it.instance) {
            is RootComponent.BottomSheet.First -> FirstContent(child)
            is RootComponent.BottomSheet.Second -> SecondContent(child)
        }
    }

ModalBottomSheetLayout(
    sheetContent = sheetState.sheetContent.value,
    sheetState = sheetState.sheetState,
) {
    // Your main content here
}
```

The example above solves some issues - e.g. the animation being interrupted when the bottom sheet is swiped away by the user, or the sheet content Composable function staying in composition forever.

**Comment by AJIEKCX** [comment] 2022-11-16 04:03
Thanks a lot, your solution looks much better! Next problem is to understand how to do the same on SwiftUi)

**Comment by arkivanov** [comment] 2022-11-16 09:30
Stay tuned, I'm going to add an alert example today. Sheets should be pretty similar I guess.

**Comment by arkivanov** [comment] 2022-11-16 20:16
I have added an alert example on iOS - #263

**Comment by AJIEKCX** [comment] 2022-11-17 08:57
Thank you again, I tried to implement a similar solution but for bottom sheet. You are right, it's pretty similar to alert extension. May be it will help someone:

```swift
extension View {
    @ViewBuilder
    func sheet<T, Content>(
        item: T?,
        onDismiss: @escaping () -> Void,
        @ViewBuilder content: @escaping (T) -> Content
    ) -> some View where Content: View {
        sheet(
            isPresented: Binding(get: { item != nil }, set: {_,_ in }),
            onDismiss: onDismiss,
            content: { content(item!) }
        )
    }
}
```

**Comment by arkivanov** [comment] 2022-11-17 09:49
Thanks for sharing! Closing this issue for now.

**Closed as not planned by arkivanov** 2022-11-17 09:49 UTC

**Comment by AJIEKCX** [comment] 2022-12-13 13:02
Hi, I've found the bug with `ModalBottomSheetOverlay` when overlayState is not synchronized with ui state of the bottom sheet. This situation can be reproduced when we intercept the hiding of the bottom sheet with a gesture and it remains on the screen, but at the same time overlayState.overlay is null. 

I haven't found any easy way to disable gesture handling on the bottom sheet while it is hiding. So far, the easiest workaround is to remove the hiding animation, for example:
```kotlin
private suspend fun ModalBottomSheetState.internalHide() {
    snapTo(ModalBottomSheetValue.Hidden)
}
```

**Comment by arkivanov** [comment] 2022-12-13 13:16
@AJIEKCX thanks for reporting that! This looks like a bug in Jetpack Compose, it should be reproducible without Decompose, by e.g. using a simple `mutableStateOf` for holding the state. Decompose adds no magic here. It would be good if you create a reproducer for the bug so we could report it to the Jetpack Compose team.
